# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8d66aaa2-fc0b-4e79-87b3-d49f881bd1ef";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-8d66aaa2-fc0b-4e79-87b3-d49f881bd1ef".device = "/dev/disk/by-uuid/8d66aaa2-fc0b-4e79-87b3-d49f881bd1ef";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-8d66aaa2-fc0b-4e79-87b3-d49f881bd1ef";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-8d66aaa2-fc0b-4e79-87b3-d49f881bd1ef";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BA42-668F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ef0bd52e-5d38-4557-b984-dd5dccef00c7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
